### ISSUE TITLE
Connection Error!

### ISSUE THREAD

**Issue by rajat709** [unboundedsystems/k3s-dind#13]
Hi,

I have followed the readme guide to run k3s-dind, But I am geting this error please help me to resolve this!

```
ubuntu@ip-172-31-5-110:~$ docker run -d --privileged --name k3s --hostname k3s -p 8443:8443 unboundedsystems/k3s-dind
9be495b718213a2cea8dcff8d8f0f71e38b9913431085033de6acb0e8bf8415d
ubuntu@ip-172-31-5-110:~$ docker exec k3s get-kubeconfig.sh > ./k3sconfig
ubuntu@ip-172-31-5-110:~$ export KUBECONFIG=./k3sconfig
ubuntu@ip-172-31-5-110:~$ kubectl get nodes
E0202 21:49:20.048811   12087 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:8443/api?timeout=32s": read tcp 127.0.0.1:54418->127.0.0.1:8443: read: connection reset by peer - error from a previous attempt: read tcp 127.0.0.1:54406->127.0.0.1:8443: read: connection reset by peer
E0202 21:49:30.056805   12087 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:8443/api?timeout=32s": read tcp 127.0.0.1:48226->127.0.0.1:8443: read: connection reset by peer - error from a previous attempt: read tcp 127.0.0.1:48222->127.0.0.1:8443: read: connection reset by peer
E0202 21:49:40.066146   12087 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:8443/api?timeout=32s": read tcp 127.0.0.1:50506->127.0.0.1:8443: read: connection reset by peer - error from a previous attempt: read tcp 127.0.0.1:50494->127.0.0.1:8443: read: connection reset by peer
```

**Comment by mterrel** [comment]
Hi there!

Unfortunately, we haven't seen a lot of interest in this project, so we haven't continued keeping it up to date. The Kubernetes version it uses is a few years old now. So I suspect the problem is related to version incompatibility between your local version of kubectl and the Kubernetes in this project.

But depending on what you want to accomplish, there may be a couple of solutions:

- The easiest is to try using the version of kubectl from the container. You should be able to do that by substituting the following instead of `kubectl`:

    `docker exec -it k3s k3s kubectl`

  Note that there is a repeated `k3s` in that command (the first one is the name of the container you started).

- You could download an older version of kubectl for your local system. I believe the version this project currently uses is v1.18.
- Fork the repo and update Kubernetes within the project so you can use a newer version.

I hope that helps!

**Comment by rajat709** [comment]
Thanks @mterrel 

It worked!!
